#!/usr/bin/env bash
#
# Qlite v002 bootstrap — the thin, bare-metal entry point (C++26 world).
#
# Shell is unavoidable here: you cannot run a compiled tool before you have a
# compiler. This stays small: it senses the host, checks the baseline, and — if a
# prerequisite is missing — generates a reviewable Setup.sh from Setup/recipes.conf
# and stops. Otherwise it configures, builds, and runs the test suite (ctest).
#
#   1. Detect the OS family (mirrors Setup::sense_host tokens).
#   2. Find a C++26 g++ (>= 14) and the activation prefix needed to invoke it.
#   3. If a baseline prerequisite is missing -> write Setup.sh and stop (run it by hand).
#   4. Otherwise -> cmake configure + build + ctest. Add --modules for the C++26 module build.
#
# Re-run after Setup.sh. Idempotent.
set -eu

ROOT="$(cd "$(dirname "$0")" && pwd)"
RECIPES="$ROOT/Setup/recipes.conf"
BUILD="$ROOT/build-bootstrap"
WANT_MODULES=0
for arg in "$@"; do
  case "$arg" in
    --modules) WANT_MODULES=1 ;;
    *) echo "unknown arg: $arg (supported: --modules)"; exit 2 ;;
  esac
done

lc() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]'; }

# --- 1. detect OS family (tokens match Setup/recipes.conf + compilers.conf) ---
family="unknown"
if [ -r /etc/os-release ]; then
  # shellcheck disable=SC1091
  . /etc/os-release 2>/dev/null || true
  id_l=$(lc "${ID:-}"); like_l=$(lc "${ID_LIKE:-}"); pretty_l=$(lc "${PRETTY_NAME:-}")
  case "$id_l" in
    linuxmint) family=linuxmint ;;
    fedora)    family=fedora ;;
    rhel|centos|rocky|almalinux|ol|scientific|sl) family=rhel ;;
    *)
      case "$pretty_l" in *"linux mint"*) family=linuxmint ;; esac
      case "$like_l" in *rhel*|*fedora*) [ "$family" = unknown ] && family=rhel ;; esac
      [ "$family" = unknown ] && [ -n "$id_l" ] && family="$id_l"
      ;;
  esac
fi
echo "Platform family: $family"

# --- enable a UTF-8 console so output renders (not mojibake) ---
# Reports + logs are plain UTF-8 (═ · –): they render in editors (gedit, VS Code) AND on
# GitHub. ANSI colour is terminal-native and lives only in live console output, never in
# files (an editor shows raw escape bytes). UTF-8 just needs a locale — prefer an already
# -UTF-8 LC_*/LANG, else fall back to C.UTF-8. The export carries into the build + tests.
enable_utf8_console() {
  case "${LC_ALL:-${LANG:-}}" in
    *UTF-8*|*UTF8*|*utf-8*|*utf8*) return 0 ;;   # already UTF-8
  esac
  if locale -a 2>/dev/null | grep -qiE '^C\.UTF-?8$'; then
    export LANG=C.UTF-8 LC_ALL=C.UTF-8
  elif locale -a 2>/dev/null | grep -qiE 'en_US\.UTF-?8$'; then
    export LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
  else
    echo "WARNING: no UTF-8 locale found — UTF-8 box-drawing output may render as mojibake."
    echo "  Install one (Fedora/RHEL: sudo dnf install glibc-langpack-en;"
    echo "  Debian/Mint: sudo locale-gen en_US.UTF-8), then re-run."
    return 0
  fi
  echo "Console: UTF-8 enabled (LANG=$LANG)"
}
enable_utf8_console

# look up an install command from recipes.conf:  recipe_cmd <component> <family>
recipe_cmd() {
  [ -r "$RECIPES" ] || return 1
  sed -n "s/^[[:space:]]*$1\\.$2[[:space:]]*=[[:space:]]*//p" "$RECIPES" | head -n1
}

ninja_ok() {
  v=$(ninja --version 2>/dev/null) && [ -n "$v" ] \
    && [ "$(printf '1.11\n%s\n' "$v" | sort -V | head -n1)" = "1.11" ]
}

# --- 2. find a C++26 g++ (>= 14) and the activation prefix needed to invoke it ---
CXX=""; ACT=""
try_cxx() {  # $1 = activation prefix (may be empty), $2 = compiler name
  p=$($1 sh -c "command -v $2" 2>/dev/null) || return 1
  [ -n "$p" ] || return 1
  major=$($1 "$2" -dumpversion 2>/dev/null | cut -d. -f1) || return 1
  case "$major" in ''|*[!0-9]*) return 1 ;; esac
  [ "$major" -ge 14 ] || return 1
  CXX="$p"; ACT="$1"; return 0
}
try_cxx "" g++-16 \
  || try_cxx "" g++-15 \
  || try_cxx "" g++-14 \
  || try_cxx "gcc-toolset-15-env" g++ \
  || try_cxx "scl enable gcc-toolset-15 --" g++ \
  || try_cxx "gcc-toolset-14-env" g++ \
  || try_cxx "scl enable gcc-toolset-14 --" g++ \
  || try_cxx "" g++ \
  || true

# --- 3. baseline check; generate Setup.sh if anything is missing ---
missing=""
[ -n "$CXX" ]                    || missing="$missing gcc15"
command -v cmake >/dev/null 2>&1 || missing="$missing cmake"
ninja_ok                         || missing="$missing ninja"
[ -e /usr/include/sqlite3.h ]    || missing="$missing sqlite"

if [ -n "$missing" ]; then
  echo "Baseline missing:$missing"
  {
    echo "#!/usr/bin/env bash"
    echo "# Auto-generated by Qlite bootstrap on $(date -u +%Y-%m-%dT%H:%M:%SZ) — REVIEW first."
    echo "# Installs the baseline needed to build Qlite v002 on family: $family"
    echo "# These commands modify your system and usually need sudo. Read them."
    echo "set -euo pipefail"
    echo
    for comp in $missing; do
      cmd=$(recipe_cmd "$comp" "$family" || true)
      if [ -n "$cmd" ]; then
        echo "# $comp"; echo "$cmd"; echo
      else
        echo "# WARNING: no recipe for '$comp' on family '$family' — install it manually."; echo
      fi
    done
    echo "echo 'Baseline installed. Re-run: ./bootstrap.sh'"
  } > "$ROOT/Setup.sh"
  chmod +x "$ROOT/Setup.sh"
  echo
  echo "Wrote Setup.sh. Review it, then run it by hand:"
  echo "  bash Setup.sh"
  echo "When it finishes, re-run: ./bootstrap.sh"
  exit 1
fi

echo "Bootstrap compiler: ${ACT:+[$ACT] }$CXX"
echo "Ninja: $(ninja --version)   CMake: $(cmake --version | head -n1)"

# --- 4. configure + build + ctest ---
CMAKE_ARGS="-G Ninja -S $ROOT -B $BUILD -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=Debug"
if [ "$WANT_MODULES" = "1" ]; then
  CMAKE_ARGS="$CMAKE_ARGS -DQLITE_BUILD_MODULES=ON"
  echo "=== configuring (with C++26 modules) ==="
else
  echo "=== configuring (textual) ==="
fi
# shellcheck disable=SC2086
$ACT cmake $CMAKE_ARGS
echo "=== building ==="
$ACT cmake --build "$BUILD"
echo "=== running tests ==="
$ACT ctest --test-dir "$BUILD" --output-on-failure

echo
echo "Bootstrap complete. Qlite v002 built and tested in: $BUILD"
echo "  Re-run the tests any time:  ctest --test-dir $BUILD --output-on-failure"
